/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-gray-50',
    'text-gray-900',
    'bg-white',
    'shadow-lg',
    'rounded-lg',
    'p-6',
    'max-w-md',
    'mx-auto',
    'mt-8',
    'space-y-4',
    'text-center',
    'text-2xl',
    'font-bold',
    'text-gray-800',
    'mb-6',
    'text-sm',
    'font-medium',
    'text-gray-700',
    'block',
    'w-full',
    'px-3',
    'py-2',
    'border',
    'border-gray-300',
    'rounded-md',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-500',
    'focus:border-transparent',
    'mt-1',
    'mb-4',
    'bg-blue-600',
    'hover:bg-blue-700',
    'text-white',
    'font-medium',
    'py-2',
    'px-4',
    'rounded-md',
    'transition',
    'duration-200',
    'w-full',
    'text-xs',
    'text-gray-600',
    'mt-4',
    'text-blue-600',
    'hover:text-blue-800'
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        }
      },
      fontFamily: {
        'arabic': ['Cairo', 'Arial', 'sans-serif'],
      },
      direction: {
        'rtl': 'rtl',
      }
    },
  },
  plugins: [],
}